'use strict';
const $ = (s) => document.querySelector(s);
const $$ = (s) => Array.from(document.querySelectorAll(s));
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = (n,d=1) => typeof n === 'number' && Number.isFinite(n) ? n.toLocaleString('es-CO',{minimumFractionDigits:d,maximumFractionDigits:d}) : '—';
const names = {spot:'SpotMicro / Rex', pepper:'Pepper', nao:'NAO'};
const leds = ['player-1','player-2','player-3','sim-spot','sim-pepper','sim-nao'];
const pins = [16,17,18,19,21,22];
const views = {inicio:['Vista general','Todo el laboratorio, conectado.'],carreras:['Zona de carreras','Tres mandos. Una misma pista.'],robotica:['Zona robótica','Del mando al movimiento.'],red:['Red y monitoreo','Cada señal cuenta una historia.'],montaje:['Montajes ESP32','Conecta cada pieza.']};
let current = 'inicio', robot = 'spot', state = null, meta = null, online = false;
const zones = {}, jointHistory = {spot:[],pepper:[],nao:[]};
let pendingState = false, pendingZone = false;
const modes = {};
function chip(s){return '<span class="chip '+esc(['OK','LENTO','CAIDO'].includes(s)?s:'')+'">'+esc(s || 'SIN DATO')+'</span>';}
function setView(v){if(!views[v])v='inicio';current=v;$$('[data-page]').forEach(x=>x.hidden=x.dataset.page!==v);$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#page-title').textContent=views[v][1];$('#crumb').textContent=views[v][0];history.replaceState(null,'','#'+v);window.scrollTo(0,0);pollZones();refreshFrames();drawCharts();}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));
$('#robot-overview').innerHTML=Object.entries(names).map(([id,n],i)=>'<article class="card robot-tile"><div class="card-head"><h3>'+n+'</h3><span id="robot-chip-'+id+'" class="chip">—</span></div><div class="frame"><img data-feed="'+id+'" alt="Render PyBullet de '+n+'"><span class="frame-status"></span></div><div class="tile-caption"><span id="robot-summary-'+id+'">Esperando telemetría</span><button class="text-button" data-open-robot="'+id+'">Explorar ↗</button></div></article>').join('');
$$('[data-open-robot]').forEach(b=>b.onclick=()=>{chooseRobot(b.dataset.openRobot);setView('robotica');});
$('#gamer-controls').innerHTML=[1,2,3].map(i=>'<article class="card gamer-card"><p class="eyebrow">CTRL-'+i+' · UDP 500'+i+'</p><h3>Jugador '+i+'</h3><p id="gamer-state-'+i+'" class="subtle">Esperando estado</p><div class="control-actions"><button class="button primary" data-gamer="'+i+'" data-mode="auto">Piloto automático</button><button class="button secondary" data-gamer="'+i+'" data-mode="pausa">Pausar mando</button></div></article>').join('');
$$('[data-gamer]').forEach(b=>b.onclick=()=>sendControl('ctrl-'+b.dataset.gamer,{modo:b.dataset.mode}));
function chooseRobot(id){robot=id;$$('[data-robot]').forEach(b=>b.classList.toggle('selected',b.dataset.robot===id));$('#robot-title').textContent=names[id];$('#robot-main-image').dataset.feed=id;$('#robot-main-image').removeAttribute('src');$('#robot-main-image').dataset.busy='';$('#robot-model-note').textContent=id==='spot'?'Modelo Rex de rex-gym · mallas SpotMicro':'URDF qiBullet · visualización con geometría simplificada';const r=id==='spot'?[[-20,20,0],[-20,20,0],[-20,20,0]]:[[-80,80,0],[2,85,44],[-70,70,0]];const labels=id==='spot'?['Altura (entrada equivalente)','Cabeceo','Alabeo']:['Hombro derecho','Codo derecho','Giro de cabeza'];$('#robot-sliders').innerHTML=r.map((v,i)=>'<div class="slider-field"><label for="joint-'+i+'">j'+(i+1)+' / '+labels[i]+'<output id="output-'+i+'">'+v[2]+'°</output></label><input id="joint-'+i+'" type="range" min="'+v[0]+'" max="'+v[1]+'" value="'+v[2]+'" step="1"></div>').join('');r.forEach((_,i)=>$('#joint-'+i).oninput=e=>$('#output-'+i).textContent=e.target.value+'°');$('#control-message').textContent='';applyControlAccess();renderRobot();refreshFrames();}
$$('[data-robot]').forEach(b=>b.onclick=()=>chooseRobot(b.dataset.robot));
function notify(text){const el=$('#toast');el.textContent=text;el.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.hidden=true,4000);}
async function sendControl(role,payload){try{const r=await fetch('/api/control/'+role,{method:'POST',headers:{'Content-Type':'application/json','X-Nexo-Control':'1'},body:JSON.stringify(payload),signal:AbortSignal.timeout(3500)});const data=await r.json();if(!r.ok)throw Error(data.error || 'No se pudo enviar');modes[role]=data.modo;const text=role+' · '+({auto:'patrón automático activo',pausa:'envío de control pausado',manual:'posición manual enviada'}[data.modo]||'actualizado');notify(text);$('#control-message').textContent=text;return data;}catch(e){notify(e.message);$('#control-message').textContent=e.message;return null;}}
$('#apply-robot').onclick=()=>sendControl('ctrl-'+robot,{modo:'manual',entradas:[0,1,2].map(i=>Number($('#joint-'+i).value)).concat(0)});
$('#auto-robot').onclick=()=>sendControl('ctrl-'+robot,{modo:'auto'});
$('#pause-robot').onclick=()=>sendControl('ctrl-'+robot,{modo:'pausa'});
function applyControlAccess(){const disabled=!meta || !meta.control_emulado || !online;$$('[data-gamer],#apply-robot,#auto-robot,#pause-robot,#robot-sliders input').forEach(b=>b.disabled=disabled);if(meta&&!meta.control_emulado)$('#control-message').textContent='Modo físico: utiliza los joysticks y potenciómetros de las ESP32.';}
const wiring={gamer:[['GPIO 34','Joystick VRx / dirección'],['GPIO 35','Joystick VRy / velocidad'],['GPIO 32','SW del joystick a GND'],['3V3','Alimentación del joystick'],['GND','Tierra común']],robot:[['GPIO 34','Cursor del potenciómetro j1'],['GPIO 35','Cursor del potenciómetro j2'],['GPIO 39 / VN','Cursor j3 (opcional)'],['GPIO 32','Pulsador a GND'],['3V3 / GND','Extremos de cada potenciómetro']],esclava:pins.map((p,i)=>['GPIO '+p,'LED '+(i+1)+' / '+leds[i]]).concat([['220 Ω / LED','Una resistencia por LED a GND']])};
function showMount(kind){$('#mount-image').src='/montaje-'+kind+'.png';$('#mount-image').alt='Ilustración de montaje generada con IA: '+kind;$('#pin-table').innerHTML=wiring[kind].map(p=>'<tr><td>'+p[0]+'</td><td>'+p[1]+'</td></tr>').join('');$$('[data-mount]').forEach(b=>b.classList.toggle('selected',b.dataset.mount===kind));}
$$('[data-mount]').forEach(b=>b.onclick=()=>showMount(b.dataset.mount));
function eventRows(events,limit){if(!events.length)return '<div class="empty">Todavía no se han registrado cambios.</div>';return events.slice(-limit).reverse().map(e=>'<div class="event-row"><time>'+new Date(e.t*1000).toLocaleTimeString('es-CO',{hour12:false})+'</time><strong>'+esc(e.servicio)+'</strong><span class="event-reason">'+esc(e.motivo)+'</span>'+chip(e.estado)+'</div>').join('');}
function observedProbe(){const all=state?.sondeos_extra || {};const extra=Object.entries(all)[0];if(extra)return {name:extra[0],...extra[1]};const x=state?.servicios?.['track-server']?.ping;return x?{name:'track-server',...x}:{};}
function render(){if(!state)return;meta=state.nexo;const services=state.servicios||{};const monitored=['track-server',...leds];const live=monitored.filter(n=>services[n]?.estado==='OK').length;const hb=Object.values(services).reduce((sum,s)=>sum+(s.hb?.recibidos||0),0);const probe=observedProbe();const ss=[['Servicios en estado OK',live+' <small>/ 7</small>','Pista, jugadores y robots','◈'],['Zonas configuradas','03','Gamer · Robótica · Administración','◎'],['Latidos recibidos',fmt(hb,0),'Contadores de los servicios','↗'],['RTT observado',fmt(probe.rtt_ultimo_ms,3)+' <small>ms</small>',probe.name||'Sin muestra disponible','↔']];$('#overview-stats').innerHTML=ss.map(s=>'<div class="stat"><span class="mini-icon">'+s[3]+'</span><span class="stat-label">'+s[0]+'</span><strong>'+s[1]+'</strong><small>'+esc(s[2])+'</small></div>').join('');
$('#scope-text').textContent=meta.modo==='software'?'PRUEBA DE SOFTWARE · ESP32 emuladas · procesos locales / loopback':meta.modo==='emulado'?'MODO EMULADO · mandos virtuales · redes configuradas en Docker':'MODO FÍSICO · entradas desde las ESP32';$('#session-time').textContent='SESIÓN '+fmt(state.en_marcha_s,0)+' s';$('#mqtt-chip').textContent=state.mqtt_conectado?'MQTT conectado':'MQTT sin conexión';$('#mqtt-chip').className='chip '+(state.mqtt_conectado?'OK':'CAIDO');
$('#led-bank').innerHTML=leds.map((n,i)=>{const s=online?(services[n]?.estado||'?'):'?';return '<div class="led-item"><span class="led-lamp '+esc(s)+'"></span><small>'+n+'</small><small class="subtle">GPIO '+pins[i]+' · '+esc(s)+'</small></div>';}).join('');
const slave=state.otras_metricas?.esclava;if(slave&&slave.edad_s<6){const matches=leds.filter(n=>slave.datos.leds?.[n]===services[n]?.estado).length;$('#slave-confirm').textContent='Esclava emulada: '+matches+'/6 estados coinciden con MQTT · última lectura '+fmt(slave.edad_s)+' s.';}else $('#slave-confirm').textContent=meta.modo==='fisico'?'Indicadores publicados; la luz física se comprueba en la placa.':'Sin confirmación reciente de la esclava emulada.';
$('#recent-events').innerHTML=eventRows(state.eventos||[],3);$('#all-events').innerHTML=eventRows(state.eventos||[],14);
$('#service-table').innerHTML=Object.entries(services).map(([n,s])=>'<tr><td><strong>'+esc(n)+'</strong><small>'+esc(s.ip)+'</small></td><td>VLAN '+s.vlan+'</td><td>'+((meta.modo==='software'&&n==='router')?'<span class="chip">SIN ENSAYO</span>':chip(s.estado))+'</td><td>'+fmt(s.hb?.edad_s,1)+' s</td><td>'+fmt(s.ping?.rtt_p95_ms,3)+' ms</td><td>'+fmt(s.hb?.jitter_ms,2)+' ms</td><td>'+fmt(s.hb?.recibidos,0)+'</td></tr>').join('');
$('#topology-note').textContent=meta.modo==='software'?'Diagrama del despliegue previsto. Esta sesión usa loopback: el aislamiento entre redes y las etiquetas 802.1Q requieren una prueba de despliegue.':'Docker Desktop utiliza tres bridges. La variante 802.1Q requiere Linux y una red física compatible. El diagrama describe la política; comprueba el aislamiento con el script de pruebas.';
$('#probe-label').textContent=(state.sondeo_transporte==='udp'?'UDP · ':'ICMP · ')+(probe.name||'Sin sondeo');$('#rtt-value').textContent=fmt(probe.rtt_ultimo_ms,3);$('#network-stats').innerHTML=[['p95',fmt(probe.rtt_p95_ms,3)+' ms'],['Jitter RTT',fmt(probe.jitter_ms,3)+' ms'],['Respuestas',fmt(probe.disp_total_pct,1)+' %']].map(x=>'<div><small>'+x[0]+'</small><strong>'+x[1]+'</strong></div>').join('');
Object.keys(names).forEach(id=>{const c=$('#robot-chip-'+id),s=services['sim-'+id]?.estado;c.textContent=s||'SIN DATO';c.className='chip '+(s||'');});applyControlAccess();renderZones();drawCharts();}
function renderZones(){const race=zones.pista;if(race?.carros){if(race.pista)$('#track-spec').textContent=fmt(race.pista.perimetro,1)+' m por vuelta · '+fmt(race.pista.ancho,1)+' m de ancho · 3 sectores';const cars=[...race.carros].sort((a,b)=>a.posicion-b.posicion);$('#ranking').innerHTML=cars.map(c=>'<div class="rank-row"><span class="rank-num">'+c.posicion+'</span><div><strong>'+esc(c.nombre||c.id)+'</strong><small>'+fmt(c.vel,1)+' m/s · '+(c.failsafe&&c.id.startsWith('player')?'frenado por señal':c.id.startsWith('auto')?'autónomo':'mando activo')+'</small></div><span>'+c.vuelta+' vtas</span></div>').join('');$('#race-time').textContent=fmt(race.t,1)+' s de simulación';[1,2,3].forEach(i=>{const c=cars.find(x=>x.id==='player-'+i);if(c)$('#gamer-state-'+i).textContent=(c.failsafe?'Freno por falta de señal':'Recibiendo control')+' · '+fmt(c.vel,1)+' m/s';});}
Object.keys(names).forEach(id=>{const s=zones[id];if(s)$('#robot-summary-'+id).textContent=s.estado+' · '+fmt(s.recibidos,0)+' paquetes';});renderRobot();}
function renderRobot(){const s=zones[robot];if(!s)return;$('#robot-state').textContent=s.estado||'—';$('#robot-packets').textContent=fmt(s.recibidos,0)+' paquetes UDP';$('#robot-error').textContent='Error medio '+fmt(s.error_deg,2)+'°';$('#joint-readings').innerHTML=[0,1,2].map(i=>'<div class="joint-reading"><small>ARTICULACIÓN j'+(i+1)+'</small><strong>'+fmt(s.medido?.[i],1)+'°</strong><span>Objetivo '+fmt(s.objetivo?.[i],1)+'°</span></div>').join('');drawCharts();}
function chart(canvas,series,colors){if(!canvas||canvas.closest('[hidden]'))return;const r=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;if(r.width<10)return;canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);const c=canvas.getContext('2d');c.scale(dpr,dpr);const w=r.width,h=r.height,pad=32;const vals=series.flat().filter(Number.isFinite);const min=vals.length?Math.min(...vals):0,max=vals.length?Math.max(...vals):1;const lo=min<0?min*1.15:0,hi=Math.max(max*1.15,lo+1);c.font='9px Segoe UI';c.textAlign='left';for(let i=0;i<4;i++){let y=12+i*(h-35)/3;c.strokeStyle='#e9eee8';c.lineWidth=1;c.beginPath();c.moveTo(pad,y);c.lineTo(w-10,y);c.stroke();c.fillStyle='#94a29b';c.fillText(fmt(hi-i*(hi-lo)/3,1),0,y+3);}if(!vals.length){c.fillStyle='#708184';c.fillText('Esperando muestras medidas',pad+10,h/2);return;}series.forEach((s,k)=>{c.strokeStyle=colors[k];c.lineWidth=2;c.beginPath();let prev=false;s.forEach((v,i)=>{if(!Number.isFinite(v)){prev=false;return;}const x=pad+(w-pad-10)*i/Math.max(1,s.length-1),y=12+(h-35)*(hi-v)/(hi-lo);if(!prev)c.moveTo(x,y);else c.lineTo(x,y);prev=true;});c.stroke();});}
function drawCharts(){const h=jointHistory[robot];chart($('#joint-chart'),[h.map(x=>x[0]),h.map(x=>x[1])],['#087e80','#d97738']);const p=observedProbe();chart($('#rtt-chart'),[(p.historial||[]).map(x=>x[1])],['#087e80']);}
async function poll(){if(pendingState)return;pendingState=true;try{const r=await fetch('/api/resumen.json',{cache:'no-store',signal:AbortSignal.timeout(2500)});if(!r.ok)throw Error();state=await r.json();online=true;$('#connection').textContent='Monitor conectado';$('#connection').className='connection';$('#refresh-info').textContent='Última lectura '+new Date().toLocaleTimeString('es-CO',{hour12:false});render();}catch{online=false;$('#connection').textContent='Monitor sin respuesta';$('#connection').className='connection off';$('#refresh-info').textContent='Sin datos actuales: última lectura retenida';$$('.led-lamp').forEach(e=>e.className='led-lamp');applyControlAccess();}finally{pendingState=false;}}
async function pollZones(){if(pendingZone)return;pendingZone=true;const ids=current==='inicio'?['pista','spot','pepper','nao']:current==='carreras'?['pista']:current==='robotica'?[robot]:[];await Promise.allSettled(ids.map(async id=>{try{const r=await fetch('/api/zona/'+id+'/estado',{cache:'no-store',signal:AbortSignal.timeout(2500)});if(!r.ok)return;const data=await r.json();zones[id]=data;if(id!=='pista'&&data.objetivo){const h=jointHistory[id];h.push([data.objetivo[0],data.medido[0]]);if(h.length>60)h.shift();}}catch{}}));renderZones();pendingZone=false;}
function refreshFrames(){const images=$$('img[data-feed]').filter(img=>!img.closest('[hidden]'));images.forEach(img=>{if(img.dataset.busy)return;const frame=img.parentElement;img.dataset.busy='1';img.onload=()=>{img.dataset.busy='';frame.classList.remove('stale');};img.onerror=()=>{img.dataset.busy='';frame.classList.add('stale');frame.querySelector('.frame-status').textContent='Sin imagen actual del servicio';};img.src='/api/zona/'+img.dataset.feed+'/'+(img.dataset.resource||'cuadro')+'?t='+Date.now();});}
window.addEventListener('resize',drawCharts);
setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('es-CO',{hour12:false}),1000);
setInterval(poll,1000);setInterval(pollZones,1000);setInterval(refreshFrames,650);
chooseRobot('spot');showMount('gamer');setView(location.hash.slice(1));poll();
